
version: '3.1'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_USER=postgres_test
      - POSTGRES_DB=postgres_test
    ports:
      - 5432:5432
    volumes:
      - ./config_pg/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  logstash:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    environment:
      - LOGSTASH_JDBC_URL=jdbc:postgresql://postgres:5432/postgres_test
      - LOGSTASH_JDBC_DRIVER=org.postgresql.Driver
      - LOGSTASH_JDBC_DRIVER_JAR_LOCATION=./config_ls/postgresql.jar
      - LOGSTASH_JDBC_USERNAME=postgres_test
      - LOGSTASH_JDBC_PASSWORD=postgres_test
      - network.publish_host=127.0.0.1
      - discovery.seed_hosts=logstash
    volumes:
      - ./config_ls/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - /home/blipp/Documents/GitHub/cdc_logstash/config_ls/postgresql-9.4-1201-jdbc41.jar:/usr/share/logstash/logstash-core/lib/jars/postgresql.jar
      - ./output:/output

    ports:
      - 9600:9600
      - 5044:5044
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

    depends_on:
      - postgres
